//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceG2A {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GryPK", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GryPK : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServiceG2A.ExtensionDataObject ExtensionData1Field;
        
        private short idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazwaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string opisField;
        
        private float cenaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public Client.ServiceG2A.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nazwa {
            get {
                return this.nazwaField;
            }
            set {
                if ((object.ReferenceEquals(this.nazwaField, value) != true)) {
                    this.nazwaField = value;
                    this.RaisePropertyChanged("nazwa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string opis {
            get {
                return this.opisField;
            }
            set {
                if ((object.ReferenceEquals(this.opisField, value) != true)) {
                    this.opisField = value;
                    this.RaisePropertyChanged("opis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public float cena {
            get {
                return this.cenaField;
            }
            set {
                if ((this.cenaField.Equals(value) != true)) {
                    this.cenaField = value;
                    this.RaisePropertyChanged("cena");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtensionDataObject", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ExtensionDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GryMZ", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GryMZ : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServiceG2A.ExtensionDataObject ExtensionData1Field;
        
        private short idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazwaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string opisField;
        
        private float cenaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public Client.ServiceG2A.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nazwa {
            get {
                return this.nazwaField;
            }
            set {
                if ((object.ReferenceEquals(this.nazwaField, value) != true)) {
                    this.nazwaField = value;
                    this.RaisePropertyChanged("nazwa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string opis {
            get {
                return this.opisField;
            }
            set {
                if ((object.ReferenceEquals(this.opisField, value) != true)) {
                    this.opisField = value;
                    this.RaisePropertyChanged("opis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public float cena {
            get {
                return this.cenaField;
            }
            set {
                if ((this.cenaField.Equals(value) != true)) {
                    this.cenaField = value;
                    this.RaisePropertyChanged("cena");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UzytkownicyMZ", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UzytkownicyMZ : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServiceG2A.ExtensionDataObject ExtensionData1Field;
        
        private short idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hasloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazwiskoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string miastoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string k_pocztowyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ulicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nr_domuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nr_blokuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nr_mieszkaniaField;
        
        private byte typ_kontaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public Client.ServiceG2A.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string haslo {
            get {
                return this.hasloField;
            }
            set {
                if ((object.ReferenceEquals(this.hasloField, value) != true)) {
                    this.hasloField = value;
                    this.RaisePropertyChanged("haslo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string imie {
            get {
                return this.imieField;
            }
            set {
                if ((object.ReferenceEquals(this.imieField, value) != true)) {
                    this.imieField = value;
                    this.RaisePropertyChanged("imie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string nazwisko {
            get {
                return this.nazwiskoField;
            }
            set {
                if ((object.ReferenceEquals(this.nazwiskoField, value) != true)) {
                    this.nazwiskoField = value;
                    this.RaisePropertyChanged("nazwisko");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string miasto {
            get {
                return this.miastoField;
            }
            set {
                if ((object.ReferenceEquals(this.miastoField, value) != true)) {
                    this.miastoField = value;
                    this.RaisePropertyChanged("miasto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string k_pocztowy {
            get {
                return this.k_pocztowyField;
            }
            set {
                if ((object.ReferenceEquals(this.k_pocztowyField, value) != true)) {
                    this.k_pocztowyField = value;
                    this.RaisePropertyChanged("k_pocztowy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ulica {
            get {
                return this.ulicaField;
            }
            set {
                if ((object.ReferenceEquals(this.ulicaField, value) != true)) {
                    this.ulicaField = value;
                    this.RaisePropertyChanged("ulica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string nr_domu {
            get {
                return this.nr_domuField;
            }
            set {
                if ((object.ReferenceEquals(this.nr_domuField, value) != true)) {
                    this.nr_domuField = value;
                    this.RaisePropertyChanged("nr_domu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string nr_bloku {
            get {
                return this.nr_blokuField;
            }
            set {
                if ((object.ReferenceEquals(this.nr_blokuField, value) != true)) {
                    this.nr_blokuField = value;
                    this.RaisePropertyChanged("nr_bloku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string nr_mieszkania {
            get {
                return this.nr_mieszkaniaField;
            }
            set {
                if ((object.ReferenceEquals(this.nr_mieszkaniaField, value) != true)) {
                    this.nr_mieszkaniaField = value;
                    this.RaisePropertyChanged("nr_mieszkania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public byte typ_konta {
            get {
                return this.typ_kontaField;
            }
            set {
                if ((this.typ_kontaField.Equals(value) != true)) {
                    this.typ_kontaField = value;
                    this.RaisePropertyChanged("typ_konta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UzytkownicyPK", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UzytkownicyPK : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServiceG2A.ExtensionDataObject ExtensionData1Field;
        
        private short idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hasloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazwiskoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string miastoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string k_pocztowyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ulicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nr_domuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nr_blokuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nr_mieszkaniaField;
        
        private byte typ_kontaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public Client.ServiceG2A.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string haslo {
            get {
                return this.hasloField;
            }
            set {
                if ((object.ReferenceEquals(this.hasloField, value) != true)) {
                    this.hasloField = value;
                    this.RaisePropertyChanged("haslo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string imie {
            get {
                return this.imieField;
            }
            set {
                if ((object.ReferenceEquals(this.imieField, value) != true)) {
                    this.imieField = value;
                    this.RaisePropertyChanged("imie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string nazwisko {
            get {
                return this.nazwiskoField;
            }
            set {
                if ((object.ReferenceEquals(this.nazwiskoField, value) != true)) {
                    this.nazwiskoField = value;
                    this.RaisePropertyChanged("nazwisko");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string miasto {
            get {
                return this.miastoField;
            }
            set {
                if ((object.ReferenceEquals(this.miastoField, value) != true)) {
                    this.miastoField = value;
                    this.RaisePropertyChanged("miasto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string k_pocztowy {
            get {
                return this.k_pocztowyField;
            }
            set {
                if ((object.ReferenceEquals(this.k_pocztowyField, value) != true)) {
                    this.k_pocztowyField = value;
                    this.RaisePropertyChanged("k_pocztowy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ulica {
            get {
                return this.ulicaField;
            }
            set {
                if ((object.ReferenceEquals(this.ulicaField, value) != true)) {
                    this.ulicaField = value;
                    this.RaisePropertyChanged("ulica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string nr_domu {
            get {
                return this.nr_domuField;
            }
            set {
                if ((object.ReferenceEquals(this.nr_domuField, value) != true)) {
                    this.nr_domuField = value;
                    this.RaisePropertyChanged("nr_domu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string nr_bloku {
            get {
                return this.nr_blokuField;
            }
            set {
                if ((object.ReferenceEquals(this.nr_blokuField, value) != true)) {
                    this.nr_blokuField = value;
                    this.RaisePropertyChanged("nr_bloku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string nr_mieszkania {
            get {
                return this.nr_mieszkaniaField;
            }
            set {
                if ((object.ReferenceEquals(this.nr_mieszkaniaField, value) != true)) {
                    this.nr_mieszkaniaField = value;
                    this.RaisePropertyChanged("nr_mieszkania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public byte typ_konta {
            get {
                return this.typ_kontaField;
            }
            set {
                if ((this.typ_kontaField.Equals(value) != true)) {
                    this.typ_kontaField = value;
                    this.RaisePropertyChanged("typ_konta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="G2A.comSoap", ConfigurationName="ServiceG2A.G2AcomSoap")]
    public interface G2AcomSoap {
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        Client.ServiceG2A.LoginResponse Login(Client.ServiceG2A.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name GamesPKResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GamesPK", ReplyAction="*")]
        Client.ServiceG2A.GamesPKResponse GamesPK(Client.ServiceG2A.GamesPKRequest request);
        
        // CODEGEN: Generating message contract since element name GamesMZResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GamesMZ", ReplyAction="*")]
        Client.ServiceG2A.GamesMZResponse GamesMZ(Client.ServiceG2A.GamesMZRequest request);
        
        // CODEGEN: Generating message contract since element name place from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddGame", ReplyAction="*")]
        Client.ServiceG2A.AddGameResponse AddGame(Client.ServiceG2A.AddGameRequest request);
        
        // CODEGEN: Generating message contract since element name place from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelGame", ReplyAction="*")]
        Client.ServiceG2A.DelGameResponse DelGame(Client.ServiceG2A.DelGameRequest request);
        
        // CODEGEN: Generating message contract since element name UsersMZResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UsersMZ", ReplyAction="*")]
        Client.ServiceG2A.UsersMZResponse UsersMZ(Client.ServiceG2A.UsersMZRequest request);
        
        // CODEGEN: Generating message contract since element name UsersPKResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UsersPK", ReplyAction="*")]
        Client.ServiceG2A.UsersPKResponse UsersPK(Client.ServiceG2A.UsersPKRequest request);
        
        // CODEGEN: Generating message contract since element name place from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewUser", ReplyAction="*")]
        Client.ServiceG2A.NewUserResponse NewUser(Client.ServiceG2A.NewUserRequest request);
        
        // CODEGEN: Generating message contract since element name place from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelUser", ReplyAction="*")]
        Client.ServiceG2A.DelUserResponse DelUser(Client.ServiceG2A.DelUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceG2A.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Client.ServiceG2A.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string login, string password) {
            this.login = login;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceG2A.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Client.ServiceG2A.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GamesPKRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GamesPK", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceG2A.GamesPKRequestBody Body;
        
        public GamesPKRequest() {
        }
        
        public GamesPKRequest(Client.ServiceG2A.GamesPKRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GamesPKRequestBody {
        
        public GamesPKRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GamesPKResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GamesPKResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceG2A.GamesPKResponseBody Body;
        
        public GamesPKResponse() {
        }
        
        public GamesPKResponse(Client.ServiceG2A.GamesPKResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GamesPKResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Client.ServiceG2A.GryPK> GamesPKResult;
        
        public GamesPKResponseBody() {
        }
        
        public GamesPKResponseBody(System.Collections.Generic.List<Client.ServiceG2A.GryPK> GamesPKResult) {
            this.GamesPKResult = GamesPKResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GamesMZRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GamesMZ", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceG2A.GamesMZRequestBody Body;
        
        public GamesMZRequest() {
        }
        
        public GamesMZRequest(Client.ServiceG2A.GamesMZRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GamesMZRequestBody {
        
        public GamesMZRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GamesMZResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GamesMZResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceG2A.GamesMZResponseBody Body;
        
        public GamesMZResponse() {
        }
        
        public GamesMZResponse(Client.ServiceG2A.GamesMZResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GamesMZResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Client.ServiceG2A.GryMZ> GamesMZResult;
        
        public GamesMZResponseBody() {
        }
        
        public GamesMZResponseBody(System.Collections.Generic.List<Client.ServiceG2A.GryMZ> GamesMZResult) {
            this.GamesMZResult = GamesMZResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddGameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddGame", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceG2A.AddGameRequestBody Body;
        
        public AddGameRequest() {
        }
        
        public AddGameRequest(Client.ServiceG2A.AddGameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddGameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string place;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float price;
        
        public AddGameRequestBody() {
        }
        
        public AddGameRequestBody(string place, string name, string description, float price) {
            this.place = place;
            this.name = name;
            this.description = description;
            this.price = price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddGameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddGameResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceG2A.AddGameResponseBody Body;
        
        public AddGameResponse() {
        }
        
        public AddGameResponse(Client.ServiceG2A.AddGameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddGameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddGameResult;
        
        public AddGameResponseBody() {
        }
        
        public AddGameResponseBody(string AddGameResult) {
            this.AddGameResult = AddGameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelGameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelGame", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceG2A.DelGameRequestBody Body;
        
        public DelGameRequest() {
        }
        
        public DelGameRequest(Client.ServiceG2A.DelGameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelGameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string place;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public short id;
        
        public DelGameRequestBody() {
        }
        
        public DelGameRequestBody(string place, short id) {
            this.place = place;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelGameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelGameResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceG2A.DelGameResponseBody Body;
        
        public DelGameResponse() {
        }
        
        public DelGameResponse(Client.ServiceG2A.DelGameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelGameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DelGameResult;
        
        public DelGameResponseBody() {
        }
        
        public DelGameResponseBody(string DelGameResult) {
            this.DelGameResult = DelGameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsersMZRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsersMZ", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceG2A.UsersMZRequestBody Body;
        
        public UsersMZRequest() {
        }
        
        public UsersMZRequest(Client.ServiceG2A.UsersMZRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UsersMZRequestBody {
        
        public UsersMZRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsersMZResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsersMZResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceG2A.UsersMZResponseBody Body;
        
        public UsersMZResponse() {
        }
        
        public UsersMZResponse(Client.ServiceG2A.UsersMZResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UsersMZResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Client.ServiceG2A.UzytkownicyMZ> UsersMZResult;
        
        public UsersMZResponseBody() {
        }
        
        public UsersMZResponseBody(System.Collections.Generic.List<Client.ServiceG2A.UzytkownicyMZ> UsersMZResult) {
            this.UsersMZResult = UsersMZResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsersPKRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsersPK", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceG2A.UsersPKRequestBody Body;
        
        public UsersPKRequest() {
        }
        
        public UsersPKRequest(Client.ServiceG2A.UsersPKRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UsersPKRequestBody {
        
        public UsersPKRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsersPKResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsersPKResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceG2A.UsersPKResponseBody Body;
        
        public UsersPKResponse() {
        }
        
        public UsersPKResponse(Client.ServiceG2A.UsersPKResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UsersPKResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Client.ServiceG2A.UzytkownicyPK> UsersPKResult;
        
        public UsersPKResponseBody() {
        }
        
        public UsersPKResponseBody(System.Collections.Generic.List<Client.ServiceG2A.UzytkownicyPK> UsersPKResult) {
            this.UsersPKResult = UsersPKResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewUser", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceG2A.NewUserRequestBody Body;
        
        public NewUserRequest() {
        }
        
        public NewUserRequest(Client.ServiceG2A.NewUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string place;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public byte AccType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Street;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string City;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ZipCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string HouseNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string BlockNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string FlatNumber;
        
        public NewUserRequestBody() {
        }
        
        public NewUserRequestBody(string place, byte AccType, string Login, string Password, string Email, string Name, string Surname, string Street, string City, string ZipCode, string HouseNumber, string BlockNumber, string FlatNumber) {
            this.place = place;
            this.AccType = AccType;
            this.Login = Login;
            this.Password = Password;
            this.Email = Email;
            this.Name = Name;
            this.Surname = Surname;
            this.Street = Street;
            this.City = City;
            this.ZipCode = ZipCode;
            this.HouseNumber = HouseNumber;
            this.BlockNumber = BlockNumber;
            this.FlatNumber = FlatNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceG2A.NewUserResponseBody Body;
        
        public NewUserResponse() {
        }
        
        public NewUserResponse(Client.ServiceG2A.NewUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int NewUserResult;
        
        public NewUserResponseBody() {
        }
        
        public NewUserResponseBody(int NewUserResult) {
            this.NewUserResult = NewUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelUser", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceG2A.DelUserRequestBody Body;
        
        public DelUserRequest() {
        }
        
        public DelUserRequest(Client.ServiceG2A.DelUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string place;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public short id;
        
        public DelUserRequestBody() {
        }
        
        public DelUserRequestBody(string place, short id) {
            this.place = place;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceG2A.DelUserResponseBody Body;
        
        public DelUserResponse() {
        }
        
        public DelUserResponse(Client.ServiceG2A.DelUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DelUserResult;
        
        public DelUserResponseBody() {
        }
        
        public DelUserResponseBody(string DelUserResult) {
            this.DelUserResult = DelUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface G2AcomSoapChannel : Client.ServiceG2A.G2AcomSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class G2AcomSoapClient : System.ServiceModel.ClientBase<Client.ServiceG2A.G2AcomSoap>, Client.ServiceG2A.G2AcomSoap {
        
        public G2AcomSoapClient() {
        }
        
        public G2AcomSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public G2AcomSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public G2AcomSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public G2AcomSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceG2A.LoginResponse Client.ServiceG2A.G2AcomSoap.Login(Client.ServiceG2A.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string login1, string password) {
            Client.ServiceG2A.LoginRequest inValue = new Client.ServiceG2A.LoginRequest();
            inValue.Body = new Client.ServiceG2A.LoginRequestBody();
            inValue.Body.login = login1;
            inValue.Body.password = password;
            Client.ServiceG2A.LoginResponse retVal = ((Client.ServiceG2A.G2AcomSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceG2A.GamesPKResponse Client.ServiceG2A.G2AcomSoap.GamesPK(Client.ServiceG2A.GamesPKRequest request) {
            return base.Channel.GamesPK(request);
        }
        
        public System.Collections.Generic.List<Client.ServiceG2A.GryPK> GamesPK() {
            Client.ServiceG2A.GamesPKRequest inValue = new Client.ServiceG2A.GamesPKRequest();
            inValue.Body = new Client.ServiceG2A.GamesPKRequestBody();
            Client.ServiceG2A.GamesPKResponse retVal = ((Client.ServiceG2A.G2AcomSoap)(this)).GamesPK(inValue);
            return retVal.Body.GamesPKResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceG2A.GamesMZResponse Client.ServiceG2A.G2AcomSoap.GamesMZ(Client.ServiceG2A.GamesMZRequest request) {
            return base.Channel.GamesMZ(request);
        }
        
        public System.Collections.Generic.List<Client.ServiceG2A.GryMZ> GamesMZ() {
            Client.ServiceG2A.GamesMZRequest inValue = new Client.ServiceG2A.GamesMZRequest();
            inValue.Body = new Client.ServiceG2A.GamesMZRequestBody();
            Client.ServiceG2A.GamesMZResponse retVal = ((Client.ServiceG2A.G2AcomSoap)(this)).GamesMZ(inValue);
            return retVal.Body.GamesMZResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceG2A.AddGameResponse Client.ServiceG2A.G2AcomSoap.AddGame(Client.ServiceG2A.AddGameRequest request) {
            return base.Channel.AddGame(request);
        }
        
        public string AddGame(string place, string name, string description, float price) {
            Client.ServiceG2A.AddGameRequest inValue = new Client.ServiceG2A.AddGameRequest();
            inValue.Body = new Client.ServiceG2A.AddGameRequestBody();
            inValue.Body.place = place;
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.price = price;
            Client.ServiceG2A.AddGameResponse retVal = ((Client.ServiceG2A.G2AcomSoap)(this)).AddGame(inValue);
            return retVal.Body.AddGameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceG2A.DelGameResponse Client.ServiceG2A.G2AcomSoap.DelGame(Client.ServiceG2A.DelGameRequest request) {
            return base.Channel.DelGame(request);
        }
        
        public string DelGame(string place, short id) {
            Client.ServiceG2A.DelGameRequest inValue = new Client.ServiceG2A.DelGameRequest();
            inValue.Body = new Client.ServiceG2A.DelGameRequestBody();
            inValue.Body.place = place;
            inValue.Body.id = id;
            Client.ServiceG2A.DelGameResponse retVal = ((Client.ServiceG2A.G2AcomSoap)(this)).DelGame(inValue);
            return retVal.Body.DelGameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceG2A.UsersMZResponse Client.ServiceG2A.G2AcomSoap.UsersMZ(Client.ServiceG2A.UsersMZRequest request) {
            return base.Channel.UsersMZ(request);
        }
        
        public System.Collections.Generic.List<Client.ServiceG2A.UzytkownicyMZ> UsersMZ() {
            Client.ServiceG2A.UsersMZRequest inValue = new Client.ServiceG2A.UsersMZRequest();
            inValue.Body = new Client.ServiceG2A.UsersMZRequestBody();
            Client.ServiceG2A.UsersMZResponse retVal = ((Client.ServiceG2A.G2AcomSoap)(this)).UsersMZ(inValue);
            return retVal.Body.UsersMZResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceG2A.UsersPKResponse Client.ServiceG2A.G2AcomSoap.UsersPK(Client.ServiceG2A.UsersPKRequest request) {
            return base.Channel.UsersPK(request);
        }
        
        public System.Collections.Generic.List<Client.ServiceG2A.UzytkownicyPK> UsersPK() {
            Client.ServiceG2A.UsersPKRequest inValue = new Client.ServiceG2A.UsersPKRequest();
            inValue.Body = new Client.ServiceG2A.UsersPKRequestBody();
            Client.ServiceG2A.UsersPKResponse retVal = ((Client.ServiceG2A.G2AcomSoap)(this)).UsersPK(inValue);
            return retVal.Body.UsersPKResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceG2A.NewUserResponse Client.ServiceG2A.G2AcomSoap.NewUser(Client.ServiceG2A.NewUserRequest request) {
            return base.Channel.NewUser(request);
        }
        
        public int NewUser(string place, byte AccType, string Login, string Password, string Email, string Name, string Surname, string Street, string City, string ZipCode, string HouseNumber, string BlockNumber, string FlatNumber) {
            Client.ServiceG2A.NewUserRequest inValue = new Client.ServiceG2A.NewUserRequest();
            inValue.Body = new Client.ServiceG2A.NewUserRequestBody();
            inValue.Body.place = place;
            inValue.Body.AccType = AccType;
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.Email = Email;
            inValue.Body.Name = Name;
            inValue.Body.Surname = Surname;
            inValue.Body.Street = Street;
            inValue.Body.City = City;
            inValue.Body.ZipCode = ZipCode;
            inValue.Body.HouseNumber = HouseNumber;
            inValue.Body.BlockNumber = BlockNumber;
            inValue.Body.FlatNumber = FlatNumber;
            Client.ServiceG2A.NewUserResponse retVal = ((Client.ServiceG2A.G2AcomSoap)(this)).NewUser(inValue);
            return retVal.Body.NewUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceG2A.DelUserResponse Client.ServiceG2A.G2AcomSoap.DelUser(Client.ServiceG2A.DelUserRequest request) {
            return base.Channel.DelUser(request);
        }
        
        public string DelUser(string place, short id) {
            Client.ServiceG2A.DelUserRequest inValue = new Client.ServiceG2A.DelUserRequest();
            inValue.Body = new Client.ServiceG2A.DelUserRequestBody();
            inValue.Body.place = place;
            inValue.Body.id = id;
            Client.ServiceG2A.DelUserResponse retVal = ((Client.ServiceG2A.G2AcomSoap)(this)).DelUser(inValue);
            return retVal.Body.DelUserResult;
        }
    }
}
