//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceG2A.MZ {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UzytkownicyMZ", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UzytkownicyMZ : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hasloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazwiskoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string miastoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string k_pocztowyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ulicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nr_domuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nr_blokuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nr_mieszkaniaField;
        
        private byte typ_kontaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string haslo {
            get {
                return this.hasloField;
            }
            set {
                if ((object.ReferenceEquals(this.hasloField, value) != true)) {
                    this.hasloField = value;
                    this.RaisePropertyChanged("haslo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string imie {
            get {
                return this.imieField;
            }
            set {
                if ((object.ReferenceEquals(this.imieField, value) != true)) {
                    this.imieField = value;
                    this.RaisePropertyChanged("imie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string nazwisko {
            get {
                return this.nazwiskoField;
            }
            set {
                if ((object.ReferenceEquals(this.nazwiskoField, value) != true)) {
                    this.nazwiskoField = value;
                    this.RaisePropertyChanged("nazwisko");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string miasto {
            get {
                return this.miastoField;
            }
            set {
                if ((object.ReferenceEquals(this.miastoField, value) != true)) {
                    this.miastoField = value;
                    this.RaisePropertyChanged("miasto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string k_pocztowy {
            get {
                return this.k_pocztowyField;
            }
            set {
                if ((object.ReferenceEquals(this.k_pocztowyField, value) != true)) {
                    this.k_pocztowyField = value;
                    this.RaisePropertyChanged("k_pocztowy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ulica {
            get {
                return this.ulicaField;
            }
            set {
                if ((object.ReferenceEquals(this.ulicaField, value) != true)) {
                    this.ulicaField = value;
                    this.RaisePropertyChanged("ulica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string nr_domu {
            get {
                return this.nr_domuField;
            }
            set {
                if ((object.ReferenceEquals(this.nr_domuField, value) != true)) {
                    this.nr_domuField = value;
                    this.RaisePropertyChanged("nr_domu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string nr_bloku {
            get {
                return this.nr_blokuField;
            }
            set {
                if ((object.ReferenceEquals(this.nr_blokuField, value) != true)) {
                    this.nr_blokuField = value;
                    this.RaisePropertyChanged("nr_bloku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string nr_mieszkania {
            get {
                return this.nr_mieszkaniaField;
            }
            set {
                if ((object.ReferenceEquals(this.nr_mieszkaniaField, value) != true)) {
                    this.nr_mieszkaniaField = value;
                    this.RaisePropertyChanged("nr_mieszkania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public byte typ_konta {
            get {
                return this.typ_kontaField;
            }
            set {
                if ((this.typ_kontaField.Equals(value) != true)) {
                    this.typ_kontaField = value;
                    this.RaisePropertyChanged("typ_konta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GryMZ", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GryMZ : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazwaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string opisField;
        
        private float cenaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nazwa {
            get {
                return this.nazwaField;
            }
            set {
                if ((object.ReferenceEquals(this.nazwaField, value) != true)) {
                    this.nazwaField = value;
                    this.RaisePropertyChanged("nazwa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string opis {
            get {
                return this.opisField;
            }
            set {
                if ((object.ReferenceEquals(this.opisField, value) != true)) {
                    this.opisField = value;
                    this.RaisePropertyChanged("opis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float cena {
            get {
                return this.cenaField;
            }
            set {
                if ((this.cenaField.Equals(value) != true)) {
                    this.cenaField = value;
                    this.RaisePropertyChanged("cena");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MZ.WebServiceMZSoap")]
    public interface WebServiceMZSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        ServiceG2A.MZ.LoginResponse Login(ServiceG2A.MZ.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name GetUsersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsers", ReplyAction="*")]
        ServiceG2A.MZ.GetUsersResponse GetUsers(ServiceG2A.MZ.GetUsersRequest request);
        
        // CODEGEN: Generating message contract since element name Login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewUser", ReplyAction="*")]
        ServiceG2A.MZ.NewUserResponse NewUser(ServiceG2A.MZ.NewUserRequest request);
        
        // CODEGEN: Generating message contract since element name DelUserResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelUser", ReplyAction="*")]
        ServiceG2A.MZ.DelUserResponse DelUser(ServiceG2A.MZ.DelUserRequest request);
        
        // CODEGEN: Generating message contract since element name GetGamesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGames", ReplyAction="*")]
        ServiceG2A.MZ.GetGamesResponse GetGames(ServiceG2A.MZ.GetGamesRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddGame", ReplyAction="*")]
        ServiceG2A.MZ.AddGameResponse AddGame(ServiceG2A.MZ.AddGameRequest request);
        
        // CODEGEN: Generating message contract since element name DelGameResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelGame", ReplyAction="*")]
        ServiceG2A.MZ.DelGameResponse DelGame(ServiceG2A.MZ.DelGameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public ServiceG2A.MZ.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ServiceG2A.MZ.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceG2A.MZ.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ServiceG2A.MZ.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsers", Namespace="http://tempuri.org/", Order=0)]
        public ServiceG2A.MZ.GetUsersRequestBody Body;
        
        public GetUsersRequest() {
        }
        
        public GetUsersRequest(ServiceG2A.MZ.GetUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUsersRequestBody {
        
        public GetUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceG2A.MZ.GetUsersResponseBody Body;
        
        public GetUsersResponse() {
        }
        
        public GetUsersResponse(ServiceG2A.MZ.GetUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ServiceG2A.MZ.UzytkownicyMZ> GetUsersResult;
        
        public GetUsersResponseBody() {
        }
        
        public GetUsersResponseBody(System.Collections.Generic.List<ServiceG2A.MZ.UzytkownicyMZ> GetUsersResult) {
            this.GetUsersResult = GetUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewUser", Namespace="http://tempuri.org/", Order=0)]
        public ServiceG2A.MZ.NewUserRequestBody Body;
        
        public NewUserRequest() {
        }
        
        public NewUserRequest(ServiceG2A.MZ.NewUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte AccType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Street;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string City;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ZipCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string HouseNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string BlockNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string FlatNumber;
        
        public NewUserRequestBody() {
        }
        
        public NewUserRequestBody(byte AccType, string Login, string Password, string Email, string Name, string Surname, string Street, string City, string ZipCode, string HouseNumber, string BlockNumber, string FlatNumber) {
            this.AccType = AccType;
            this.Login = Login;
            this.Password = Password;
            this.Email = Email;
            this.Name = Name;
            this.Surname = Surname;
            this.Street = Street;
            this.City = City;
            this.ZipCode = ZipCode;
            this.HouseNumber = HouseNumber;
            this.BlockNumber = BlockNumber;
            this.FlatNumber = FlatNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceG2A.MZ.NewUserResponseBody Body;
        
        public NewUserResponse() {
        }
        
        public NewUserResponse(ServiceG2A.MZ.NewUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int NewUserResult;
        
        public NewUserResponseBody() {
        }
        
        public NewUserResponseBody(int NewUserResult) {
            this.NewUserResult = NewUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelUser", Namespace="http://tempuri.org/", Order=0)]
        public ServiceG2A.MZ.DelUserRequestBody Body;
        
        public DelUserRequest() {
        }
        
        public DelUserRequest(ServiceG2A.MZ.DelUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public short ID;
        
        public DelUserRequestBody() {
        }
        
        public DelUserRequestBody(short ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceG2A.MZ.DelUserResponseBody Body;
        
        public DelUserResponse() {
        }
        
        public DelUserResponse(ServiceG2A.MZ.DelUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DelUserResult;
        
        public DelUserResponseBody() {
        }
        
        public DelUserResponseBody(string DelUserResult) {
            this.DelUserResult = DelUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGames", Namespace="http://tempuri.org/", Order=0)]
        public ServiceG2A.MZ.GetGamesRequestBody Body;
        
        public GetGamesRequest() {
        }
        
        public GetGamesRequest(ServiceG2A.MZ.GetGamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetGamesRequestBody {
        
        public GetGamesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGamesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceG2A.MZ.GetGamesResponseBody Body;
        
        public GetGamesResponse() {
        }
        
        public GetGamesResponse(ServiceG2A.MZ.GetGamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGamesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ServiceG2A.MZ.GryMZ> GetGamesResult;
        
        public GetGamesResponseBody() {
        }
        
        public GetGamesResponseBody(System.Collections.Generic.List<ServiceG2A.MZ.GryMZ> GetGamesResult) {
            this.GetGamesResult = GetGamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddGameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddGame", Namespace="http://tempuri.org/", Order=0)]
        public ServiceG2A.MZ.AddGameRequestBody Body;
        
        public AddGameRequest() {
        }
        
        public AddGameRequest(ServiceG2A.MZ.AddGameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddGameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float price;
        
        public AddGameRequestBody() {
        }
        
        public AddGameRequestBody(string name, string description, float price) {
            this.name = name;
            this.description = description;
            this.price = price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddGameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddGameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceG2A.MZ.AddGameResponseBody Body;
        
        public AddGameResponse() {
        }
        
        public AddGameResponse(ServiceG2A.MZ.AddGameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddGameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddGameResult;
        
        public AddGameResponseBody() {
        }
        
        public AddGameResponseBody(string AddGameResult) {
            this.AddGameResult = AddGameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelGameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelGame", Namespace="http://tempuri.org/", Order=0)]
        public ServiceG2A.MZ.DelGameRequestBody Body;
        
        public DelGameRequest() {
        }
        
        public DelGameRequest(ServiceG2A.MZ.DelGameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelGameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public short ID;
        
        public DelGameRequestBody() {
        }
        
        public DelGameRequestBody(short ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelGameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelGameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceG2A.MZ.DelGameResponseBody Body;
        
        public DelGameResponse() {
        }
        
        public DelGameResponse(ServiceG2A.MZ.DelGameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelGameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DelGameResult;
        
        public DelGameResponseBody() {
        }
        
        public DelGameResponseBody(string DelGameResult) {
            this.DelGameResult = DelGameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMZSoapChannel : ServiceG2A.MZ.WebServiceMZSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMZSoapClient : System.ServiceModel.ClientBase<ServiceG2A.MZ.WebServiceMZSoap>, ServiceG2A.MZ.WebServiceMZSoap {
        
        public WebServiceMZSoapClient() {
        }
        
        public WebServiceMZSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMZSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMZSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMZSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceG2A.MZ.LoginResponse ServiceG2A.MZ.WebServiceMZSoap.Login(ServiceG2A.MZ.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string username, string password) {
            ServiceG2A.MZ.LoginRequest inValue = new ServiceG2A.MZ.LoginRequest();
            inValue.Body = new ServiceG2A.MZ.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            ServiceG2A.MZ.LoginResponse retVal = ((ServiceG2A.MZ.WebServiceMZSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceG2A.MZ.GetUsersResponse ServiceG2A.MZ.WebServiceMZSoap.GetUsers(ServiceG2A.MZ.GetUsersRequest request) {
            return base.Channel.GetUsers(request);
        }
        
        public System.Collections.Generic.List<ServiceG2A.MZ.UzytkownicyMZ> GetUsers() {
            ServiceG2A.MZ.GetUsersRequest inValue = new ServiceG2A.MZ.GetUsersRequest();
            inValue.Body = new ServiceG2A.MZ.GetUsersRequestBody();
            ServiceG2A.MZ.GetUsersResponse retVal = ((ServiceG2A.MZ.WebServiceMZSoap)(this)).GetUsers(inValue);
            return retVal.Body.GetUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceG2A.MZ.NewUserResponse ServiceG2A.MZ.WebServiceMZSoap.NewUser(ServiceG2A.MZ.NewUserRequest request) {
            return base.Channel.NewUser(request);
        }
        
        public int NewUser(byte AccType, string Login, string Password, string Email, string Name, string Surname, string Street, string City, string ZipCode, string HouseNumber, string BlockNumber, string FlatNumber) {
            ServiceG2A.MZ.NewUserRequest inValue = new ServiceG2A.MZ.NewUserRequest();
            inValue.Body = new ServiceG2A.MZ.NewUserRequestBody();
            inValue.Body.AccType = AccType;
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.Email = Email;
            inValue.Body.Name = Name;
            inValue.Body.Surname = Surname;
            inValue.Body.Street = Street;
            inValue.Body.City = City;
            inValue.Body.ZipCode = ZipCode;
            inValue.Body.HouseNumber = HouseNumber;
            inValue.Body.BlockNumber = BlockNumber;
            inValue.Body.FlatNumber = FlatNumber;
            ServiceG2A.MZ.NewUserResponse retVal = ((ServiceG2A.MZ.WebServiceMZSoap)(this)).NewUser(inValue);
            return retVal.Body.NewUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceG2A.MZ.DelUserResponse ServiceG2A.MZ.WebServiceMZSoap.DelUser(ServiceG2A.MZ.DelUserRequest request) {
            return base.Channel.DelUser(request);
        }
        
        public string DelUser(short ID) {
            ServiceG2A.MZ.DelUserRequest inValue = new ServiceG2A.MZ.DelUserRequest();
            inValue.Body = new ServiceG2A.MZ.DelUserRequestBody();
            inValue.Body.ID = ID;
            ServiceG2A.MZ.DelUserResponse retVal = ((ServiceG2A.MZ.WebServiceMZSoap)(this)).DelUser(inValue);
            return retVal.Body.DelUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceG2A.MZ.GetGamesResponse ServiceG2A.MZ.WebServiceMZSoap.GetGames(ServiceG2A.MZ.GetGamesRequest request) {
            return base.Channel.GetGames(request);
        }
        
        public System.Collections.Generic.List<ServiceG2A.MZ.GryMZ> GetGames() {
            ServiceG2A.MZ.GetGamesRequest inValue = new ServiceG2A.MZ.GetGamesRequest();
            inValue.Body = new ServiceG2A.MZ.GetGamesRequestBody();
            ServiceG2A.MZ.GetGamesResponse retVal = ((ServiceG2A.MZ.WebServiceMZSoap)(this)).GetGames(inValue);
            return retVal.Body.GetGamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceG2A.MZ.AddGameResponse ServiceG2A.MZ.WebServiceMZSoap.AddGame(ServiceG2A.MZ.AddGameRequest request) {
            return base.Channel.AddGame(request);
        }
        
        public string AddGame(string name, string description, float price) {
            ServiceG2A.MZ.AddGameRequest inValue = new ServiceG2A.MZ.AddGameRequest();
            inValue.Body = new ServiceG2A.MZ.AddGameRequestBody();
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.price = price;
            ServiceG2A.MZ.AddGameResponse retVal = ((ServiceG2A.MZ.WebServiceMZSoap)(this)).AddGame(inValue);
            return retVal.Body.AddGameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceG2A.MZ.DelGameResponse ServiceG2A.MZ.WebServiceMZSoap.DelGame(ServiceG2A.MZ.DelGameRequest request) {
            return base.Channel.DelGame(request);
        }
        
        public string DelGame(short ID) {
            ServiceG2A.MZ.DelGameRequest inValue = new ServiceG2A.MZ.DelGameRequest();
            inValue.Body = new ServiceG2A.MZ.DelGameRequestBody();
            inValue.Body.ID = ID;
            ServiceG2A.MZ.DelGameResponse retVal = ((ServiceG2A.MZ.WebServiceMZSoap)(this)).DelGame(inValue);
            return retVal.Body.DelGameResult;
        }
    }
}
